kubecostProductConfigs:
  clusterName: AWS_kubecostProductConfigs_clusterName
  # productKey:
  #   secretname: productkey
  #   enabled: false #not needed for eval
  serviceKeySecretName: aws-service-key
  projectID: "AWS_kubecostProductConfigs_projectID"
  awsSpotDataRegion: AWS_kubecostProductConfigs_awsSpotDataRegion
  awsSpotDataBucket: AWS_kubecostProductConfigs_awsSpotDataBucket
kubecostModel:
  warmCache: false
  warmSavingsCache: false
  etl: false
global:
  grafana:
    enabled: false
    proxy: false
prometheus:
  server:
    global:
      external_labels:
        cluster_id: kubecostProductConfigs_clusterName
networkCosts:
  enabled: true