# This values file contains all of the images kubecost requires.
# Kubecost has monthly releases and patches to address any issues.
# To get a dynamic list of current images, run the following script:
# install yq with brew / pip / etc
# helm template kubecost --repo https://kubecost.github.io/cost-analyzer/ kubecost --set networkCosts.enabled=true --set clusterController.enabled=true | yq '..|.image? | select(.)' | sort -u
# If you don't have yq this should output the same:
# helm template kubecost --repo https://kubecost.github.io/cost-analyzer/ kubecost --set networkCosts.enabled=true --set clusterController.enabled=true | grep 'image:'|sed 's/image: //g'|sed 's/"//g'|sed 's/- //g'|sed 's/ //g'|sort -u
# if you use docker to pull images, you can use the output to pull the images:
# (previous_command)| xargs -I {} docker pull {}

# Images from https://github.com/kubecost/cost-analyzer-helm-chart/tree/develop/cost-analyzer
# imagePullSecrets:
# - name: "image-pull-secret"

imageVersion: "prod-2.2.2" # If set, overrides default of $.Chart.AppVersion. Ignored if setting fullImageName for each Kubecost image.

kubecostFrontend:
  # fullImageName: YOUR_REGISTRY/frontend:prod-1.104.0
  image: "YOUR_REGISTRY/frontend"
  imagePullPolicy: Always

kubecostModel:
  # fullImageName: "YOUR_REGISTRY/cost-model:prod-1.104.0" # Use image -OR- fullImageName.
  image: "YOUR_REGISTRY/cost-model"
  imagePullPolicy: Always

forecasting:
  fullImageName: YOUR_REGISTRY/kubecost-modeling:v0.1.6

networkCosts:
  image: YOUR_REGISTRY/kubecost-network-costs:v17.3  # Always the full image path with version tag.
  imagePullPolicy: Always

# Kubecost Cluster Controller for Right Sizing and Cluster Turndown
clusterController:
  image: YOUR_REGISTRY/cluster-controller:v0.16.0 # Always the full image path with version tag.
  imagePullPolicy: Always

# initChownDataImage: "busybox" # Supports a fully qualified Docker image, e.g. registry.hub.docker.com/library/busybox:latest

## Images from https://github.com/kubecost/cost-analyzer-helm-chart/tree/develop/cost-analyzer/charts/prometheus
prometheus:
  # imagePullSecrets:
  # - name: "image-pull-secret"

  server:
    image:
      repository: YOUR_REGISTRY/prometheus
      tag: v2.51.2
      pullPolicy: IfNotPresent


  # alertmanager:
  #   image:
  #     repository: YOUR_REGISTRY/alertmanager
  #     tag: v0.23.0
  #     pullPolicy: IfNotPresent

  # configmapReload:
  #   prometheus:
  #     image:
  #       repository: YOUR_REGISTRY/configmap-reload
  #       tag: v0.7.1
  #       pullPolicy: IfNotPresent
    # alertmanager:
    #   image:
    #     repository: YOUR_REGISTRY/configmap-reload
    #     tag: v0.7.1
    #     pullPolicy: IfNotPresent

  nodeExporter:
# node exporter is optional. in multi cluster, there is no value to running it:
    enabled: false
    # if required:
    image:
      repository: YOUR_REGISTRY/node-exporter
      tag: v1.7.0
      pullPolicy: IfNotPresent
  # pushgateway is not enabled by default
  # pushgateway:
  #   image:
  #     repository: YOUR_REGISTRY/pushgateway
  #     tag: v1.4.2
  #     pullPolicy: IfNotPresent

## Images from https://github.com/kubecost/cost-analyzer-helm-chart/tree/develop/cost-analyzer/charts/grafana
grafana:
  image:
    repository: YOUR_REGISTRY/grafana
    tag: 10.4.1
    pullPolicy: IfNotPresent
  sidecar:
    image:
      repository: YOUR_REGISTRY/k8s-sidecar
      tag: 1.26.1
      pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ##
    # pullSecrets:
    #   - myRegistryKeySecretName

  # downloadDashboardsImage:
  #   repository: YOUR_REGISTRY/curl
  #   tag: latest
  #   pullPolicy: IfNotPresent
